### ISSUE TITLE
Install vbguest

### ISSUE THREAD

**Issue by garethrees** [owainlewis/virtual-ubuntu#1]
> ```
> # Virtual Box issue 
> vagrant ssh -c 'sudo ln -s /opt/VBoxGuestAdditions-4.3.28/lib/VBoxGuestAdditions/ /usr/lib/VBoxGuestAdditions'
> ```

I think https://github.com/dotless-de/vagrant-vbguest should fix this.

**Comment by owainlewis** [comment]
Thanks. For some reason it still didn't work for me even with the vbguest plugin. Will take a look tonight to dig into the issue. :+1:

**Comment by owainlewis** [comment]
Turns out we need to install some ubuntu packages for it to work. All fixed now. 

https://github.com/owainlewis/virtual-ubuntu/blob/master/provision.sh#L13
